### ISSUE TITLE
Como contribuir?

### ISSUE THREAD

**Issue by vinisalazar** [lubianat/ptbR#1]
E aí pessoal, tudo bem?

Tem alguma orientação de como contribuir?

Pelo que entendi, basta botar o nome da função em português chamando a função em inglês, com os comentários em cima, é isso?

Vocês acham que seria interessante elaborar uma lista das funções mais interessantes a serem traduzidas?

[ ]'s
Vini

**Comment by lubianat** [comment]
Tinha uma mini orientação no README, mas foi feita às pressas.

Tem uma lista  de funções interessantes aqui que o @KleberNeves compilou e é editável: 

https://docs.google.com/spreadsheets/d/11M3_aU6aqF6_-XJMIz7jK4uii71LN018CZlBmHMLaoI/edit#gid=0

É exatamente isso. Só adicionar à pasta R um arquivo .R com as funções e a documentação em cima. 

Dá pra copiar das funções que já tão lá. 
Esse tutorial sobre pacotes do R é mega bom: https://hilaryparker.com/2014/04/29/writing-an-r-package-from-scratch/

Vale a pena dar uma olhada

valeu!

**Comment by vinisalazar** [comment]
Po, esse docs escapou. Mas show, obrigado
